### ISSUE TITLE
When dropping an item, the icon stays on the screen

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#19] opened 2023-04-13 15:09 UTC
![20230413180611_1](https://user-images.githubusercontent.com/130680276/231803507-9a640ed5-a038-4c77-8115-45e893874681.jpg)

and it claims that inventory is full (if dropping from full inventory)

**Comment by Oskutin** [comment] 2023-04-23 02:02
Can't reproduce this

**Comment by Oskutin** [comment] 2023-04-25 22:34
Duplicate of this: https://github.com/loiste-interactive/Obenseuer-Issues/issues/134

**Closed by Oskutin** 2023-04-25 22:34 UTC
Labels: duplicate
