### ISSUE TITLE
Adam is borked again

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#197] opened 2023-05-13 17:23 UTC
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/6200790e-e24c-4966-b5a5-4b191783cbf3)

**Comment by ontrigger** [comment] 2023-05-13 17:23
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11470222/Player.log)

**Comment by Oskutin** [comment] 2023-05-13 17:24
Oh great

**Comment by Oskutin** [comment] 2023-05-13 17:32
Dupe of https://github.com/loiste-interactive/Obenseuer-Issues/issues/187 ,which also explains the reason better

**Closed by Oskutin** 2023-05-13 17:32 UTC
Labels: duplicate
