### ISSUE TITLE
Bug - jail time mechanic not locking you up for correct amount of time

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1628] opened 2023-12-30 08:16 UTC
In this save, immediately turn yourself into the police officer.
[Mark_Smith.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13797489/Mark_Smith.zip)

`Tuesday 16:04` - Arrest Time
`Wednesday 15:04` - Expected release after `23h`
`16 hours` - Time remaining when I asked the guard as soon as I spawned in.
NOTE: used `Hand Console` to `Skip two hours` after talking to guard.
`Tuesday 18:55` - Actual release after putting my watch back on

https://youtu.be/iwmPePH0wjc

**Comment by DragonZephyr** [comment] 2024-05-14 04:23
Seems to be related to the 2 hour passing items or the issue is exasperated with them. Guard said it would be 4 days, sleeping and wall staring seemed to deduct hours as expected. Then spent some time with console 1-3 times was released within 1 day

**Comment by Oskutin** [comment] 2024-12-26 20:57
already fixed

**Closed by Oskutin** 2024-12-26 20:57 UTC
Labels: Bug, Prison
