### ISSUE TITLE
weird animation on the storage light switch

### ISSUE THREAD

**Issue by gehube** [loiste-interactive/Obenseuer-Issues#236] opened 2023-05-17 16:02 UTC
https://github.com/loiste-interactive/Obenseuer-Issues/assets/130682887/f1e31e81-f306-400b-a1cb-7a5ae932b1b1

-when the lights are off, the switch is in the on position
-when interacted, the switch goes down but comes back up
-turning the lights off has no animation

**Comment by Oskutin** [comment] 2023-05-17 16:06
Dupe of https://github.com/loiste-interactive/Obenseuer-Issues/issues/184

**Closed by Oskutin** 2023-05-17 16:06 UTC
Labels: duplicate
