### ISSUE TITLE
playtest - all apartments fully examine themselves when entering basement from outside 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#3189] opened 2024-12-21 00:04 UTC
auto save 1 is where it happens.
[Kyle_Pinkmin.zip](https://github.com/user-attachments/files/18216481/Kyle_Pinkmin.zip)

**Comment by Oskutin** [comment] 2024-12-21 00:17
dupe of this: https://github.com/loiste-interactive/Obenseuer-Issues/issues/3185
but keeping this as this has save file

**Comment by Orphiex** [comment] 2024-12-21 09:13
Oh yeah, this happened to me too

**Comment by Zuntti** [comment] 2024-12-30 14:43
Seems to be already fixed?

**Closed by Zuntti** 2024-12-30 14:43 UTC
Labels: Bug
