### ISSUE TITLE
After receiving Union of Lockpicks flag for the first time, it's broken to place.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1677] opened 2024-01-04 21:21 UTC
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/b05f848e-3bb1-4df4-9214-07784f030883)

**Comment by pinkamedic** [comment] 2024-01-04 21:27
i can confirm this bug but if you just leave the building then return it will work like normal

**Comment by Nextej** [comment] 2024-01-04 21:28
that doesn't excuse it from being fixed

**Comment by pinkamedic** [comment] 2024-01-04 21:29
fair enough

**Comment by pinkamedic** [comment] 2024-01-04 21:36
![Screenshot 2023-12-29 204936](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/4807d378-4457-47ce-b32c-6e4af6847228)
i experienced it aswell when you first get the item from the mail its a white box and your unable to place it, but if you leave the builiding youll be able to put it down

**Comment by Nextej** [comment] 2024-01-04 21:54
That issue was closed by its author as I recall

**Comment by CVariable** [comment] 2024-01-04 22:33
No, that was reported by me and closed as fixed, even though it only seems to be fixed sometimes. In this .27 save, the machinist flag was broken with white box, but the lockpick flag worked as it should

**Comment by Zuntti** [comment] 2024-01-08 16:04
Fixed

**Closed by Zuntti** 2024-01-08 16:04 UTC
Labels: bug
