### ISSUE TITLE
Bug: Officers don't arrest

### ISSUE THREAD

**Issue by alloysiuspercivalblack** [loiste-interactive/Obenseuer-Issues#1429] opened 2023-12-12 09:58 UTC
The police will often not arrest the player regardless of the size of their bounty, not sure what prompts them to eventually arrest you

**Comment by CVariable** [comment] 2023-12-12 15:31
The police behavior has been known to have issues after loading after the first game start. It will be fixed as soon as the devs have time. 
Duplicate of #1093

**Closed** 2023-12-12 18:31 UTC
Labels: duplicate
