### ISSUE TITLE
drill ui missing texture

### ISSUE THREAD

**Issue by gehube** [loiste-interactive/Obenseuer-Issues#20] opened 2023-04-13 15:24 UTC
![20230413182036_1](https://user-images.githubusercontent.com/130682887/231807904-deed05bd-3f8c-472b-8df3-d54fc52f4a7c.jpg)

**Comment by Oskutin** [comment] 2023-04-14 02:32
Duplicate of #7

**Closed by Oskutin** 2023-04-14 02:32 UTC
Labels: Graphical
