### ISSUE TITLE
Renovation of Tenement Heating from Makeshift to Central stuck at 0s.

### ISSUE THREAD

**Issue by Jed454** [loiste-interactive/Obenseuer-Issues#1705] opened 2024-01-07 12:56 UTC
Renovation of Tenement Heating from Makeshift to Central stuck at 0s, I was in jail when it should have progressed to final payment. Saving and rebooting doesn't fix the error. Steam discussions have mentioned the same occurrence with other renovations getting stuck at 0 seconds while in jail.
![Tenement Heating stuck at 0s](https://github.com/loiste-interactive/Obenseuer-Issues/assets/155886013/dbf97ad5-aad4-4255-8275-6629f8e80e58)
[1-7-23 Obenseuer stuck heating.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13853497/1-7-23.Obenseuer.stuck.heating.zip)

**Comment by CVariable** [comment] 2024-01-08 06:42
This is a duplicate of #1620. That issue report also contains instructions on how to fix this problem.

**Comment by Zuntti** [comment] 2024-01-08 11:19
Fixed

**Closed by Zuntti** 2024-01-08 11:19 UTC
