### ISSUE TITLE
Tenement System: Removing your own placed item causes the game to remove items with each reload.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#313] opened 2023-07-01 16:47 UTC
In your own apartment, removing items that you've placed will cause the game to remove exact number of the items you've removed with each next reload of that level, for example:
- Place 10 different objects
- Remove 4 of them
- Reload the level (resave and reload or change maps back and forth)
- 4 latest placed items will be removed
- each next reload will remove exactly 4 latest placed items

**Comment by Oskutin** [comment] 2023-07-17 00:23
Can't seem to reproduce. Either it is fixed by some other fix, or the cause mechanism is more complex

**Comment by Nextej** [comment] 2023-07-17 11:38
[Furniture_Bug.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/12068740/Furniture_Bug.zip)
character's named "Furniture Bug", savefile 3 has the bug triggered, causing one item to be removed with each reload, you can test that by placing multiply items and then reloading the level.

**Comment by Zuntti** [comment] 2023-08-01 10:37
Seems to be fixed now

**Closed by Zuntti** 2023-08-01 10:37 UTC
Labels: bug, Savegames, Tenement system
