### ISSUE TITLE
Moving backwards in the  start lobby cell causes the game screen to shake

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#127] opened 2023-04-25 17:55 UTC
I found when i pressed the S button to walk backwards in the beginning zone it would shake the screen mostly in the middle. A and D i saw also had minor shaking but not anywhere as bad as walking backwards. Forward doesn't have this issue and i've only seen it do this in this cell and not either of the other two open to us right now.   I've tried this on several fresh starts and reopening the game. 
![20230424214938_1](https://user-images.githubusercontent.com/65619937/234361573-d64ae22e-776d-4ea4-b2ab-76378a7d4241.jpg)

**Comment by Crlangley** [comment] 2023-04-25 17:56
If anyone has a way to record video and want to try this might give some better evidence for this.

**Comment by ontrigger** [comment] 2023-04-25 18:09
Duplicate of #38

**Closed** 2023-04-25 18:11 UTC
Labels: duplicate
