### ISSUE TITLE
Weird shaky movement on a doorway in Deekula A

### ISSUE THREAD

**Issue by gehube** [loiste-interactive/Obenseuer-Issues#186] opened 2023-05-13 15:42 UTC
https://github.com/loiste-interactive/Obenseuer-Issues/assets/130682887/1e333e6a-a659-457a-ab17-83513e983fb4

**Comment by Oskutin** [comment] 2023-05-21 19:48
Duplicate of: https://github.com/loiste-interactive/Obenseuer-Issues/issues/38

**Closed by Oskutin** 2023-05-21 19:48 UTC
Labels: duplicate
