### ISSUE TITLE
Can't fill bottles at sinks

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#120] opened 2023-04-24 21:48 UTC
None of the sinks I've checked have the option to fill bottles, even though each one has qualifiers in the interface (clean, dirty, etc.) that make me think I should be able to get water from them.

**Comment by Oskutin** [comment] 2023-04-24 22:06
You put the bottles on sink's inventory?

**Comment by CBS-S** [comment] 2023-04-24 22:10
I tried to but it was greyed out.

**Comment by Oskutin** [comment] 2023-04-24 22:16
Duplicate of https://github.com/loiste-interactive/Obenseuer-Issues/issues/99

**Closed by Oskutin** 2023-04-24 22:16 UTC
Labels: duplicate
