### ISSUE TITLE
Playtesting 0.3.15 - After being taken to jail by the approaching cop, once jail map is loaded all stats begin to drastically increase (including health dropping drastically), sleeping on that map fixes the stats progression.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#938] opened 2023-11-10 18:37 UTC
At first I wrongly associated that as #888

**Comment by Nextej** [comment] 2023-11-10 18:37
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13322358/Player.zip)

**Comment by Kastuk** [comment] 2023-11-10 19:35
I got similar stuff with big time skip, so all need gonna red and food on table got molded, so I ll be dead without godmode there (well, I got negative broken health anyway).

**Comment by Oskutin** [comment] 2023-11-12 14:33
Can't reproduce, and  time breaking was fixed by some code changes.
There may be some other related bugs, tho

**Closed by Oskutin** 2023-11-12 14:33 UTC
Labels: bug
