### ISSUE TITLE
[Playtesting] Cmera Shakes violently when talking to Mikkel Purola

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2986] opened 2024-12-13 16:14 UTC

**Comment by Oskutin** [comment] 2024-12-13 16:15
dupe of: https://github.com/loiste-interactive/Obenseuer-Issues/issues/2666 ?

**Comment by TonyFromRomania** [comment] 2024-12-13 16:16
yea that bung never got fixed fully

**Closed** 2024-12-13 16:17 UTC
Labels: duplicate
