### ISSUE TITLE
Mixed Ownership of items in Kolhola A7

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#727] opened 2023-11-01 18:58 UTC
Apartment A7 in Kolhola appears abandonned but has various items that are marked as "steal" and not free to take. Most items are free to take. Seems inconsistent.

**Comment by Oskutin** [comment] 2023-11-01 19:40
What items are marked as owned?

**Comment by snortico** [comment] 2023-11-01 19:45
Several in the kitchen. Macaroni meal in the fridge, macaroni in the drawer. I believe there was one more on the counter.

**Comment by Oskutin** [comment] 2023-11-01 20:13
Umm, can't reproduce this. Found that only the sink is owned

**Comment by snortico** [comment] 2023-11-01 20:14
Strange. I will go get screenshots when I am back in game if they are still owned.

**Comment by Oskutin** [comment] 2023-11-02 01:53
Ah, found the issue

**Comment by Oskutin** [comment] 2023-11-02 01:57
Fixed

**Closed by Oskutin** 2023-11-02 01:57 UTC
Labels: bug
