### ISSUE TITLE
Playtesting (0.3.43 v2) - Crafting menu list is broken

### ISSUE THREAD

**Issue by ProfRadis** [loiste-interactive/Obenseuer-Issues#3065] opened 2024-12-14 22:41 UTC
![20241215003951_1](https://github.com/user-attachments/assets/f100b664-1b13-4d7e-93e8-e269b872dbfd)
![20241215003946_1](https://github.com/user-attachments/assets/715080de-e99f-4e78-84e5-bceaa5855a32)

**Comment by ProfRadis** [comment] 2024-12-14 22:43
for example i want to craft a lockpick from sheet metal but doesn't let me to craft

**Comment by Oskutin** [comment] 2024-12-14 22:53
What does the the grayed out recipe say?

**Comment by ProfRadis** [comment] 2024-12-14 23:51
![20241215014953_1](https://github.com/user-attachments/assets/d47c9d12-9714-426c-b016-30be409f95cc)

**Comment by ProfRadis** [comment] 2024-12-14 23:52
it feels like one recipe is above but it doesn't show it

**Comment by Zuntti** [comment] 2024-12-16 13:18
Can I get a save where this happens?

**Comment by Oskutin** [comment] 2024-12-29 13:14
dupe of: https://github.com/loiste-interactive/Obenseuer-Issues/issues/2742

**Closed by Oskutin** 2024-12-29 13:14 UTC
Labels: Bug
