### ISSUE TITLE
Age old fuel slot issue (effects sinks too)

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#882] opened 2023-11-08 20:17 UTC
Makeshift heating in player appartment: Barrel stove still haven't fuel slot from start (same as Ball Grill in makeshift kitchen of other appartment).
![20231108230750_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/07b32a7c-6f2f-436b-99ef-02b729b13229)
error at open the stove:

> System.NullReferenceException
>   at (wrapper managed-to-native) UnityEngine.GameObject.SetActive(UnityEngine.GameObject,bool)
>   at Slot.HideTradeUI () [0x0000a] in <de80282032774528af67235d529e39b9>:0  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
> 
> System.NullReferenceException
>   at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
>   at SlotController.CaptureSlot () [0x0001c] in <de80282032774528af67235d529e39b9>:0 
>   at CraftingBase.Enter () [0x00038] in <de80282032774528af67235d529e39b9>:0  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Makeshift sink barrel at any appartment will inherit fuel button from any other fuel or electro (no) device opened before.
![20231108225510_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/d7e99746-5d00-44c9-964c-c228efcf3eb0)
Error when open sink after barrel stove:

> NullReferenceException
>   at (wrapper managed-to-native) UnityEngine.Behaviour.get_isActiveAndEnabled(UnityEngine.Behaviour)
>   at UnityEngine.EventSystems.UIBehaviour.IsActive () [0x00000] in <b33094dda4904923a301738eea94aa76>:0 
>   at UnityEngine.UI.Graphic.SetMaterialDirty () [0x00000] in <b33094dda4904923a301738eea94aa76>:0 
>   at UnityEngine.UI.Graphic.SetAllDirty () [0x00028] in <b33094dda4904923a301738eea94aa76>:0 
>   at UnityEngine.UI.Image.set_sprite (UnityEngine.Sprite value) [0x0008e] in <b33094dda4904923a301738eea94aa76>:0 
>   at ManufacturingPowerUI.ChangePowerSettings (System.Boolean requiresFuel, System.Boolean poweredAndActive, PowerSource+PowerSourceType powerSource, System.Boolean alwaysOn) [0x000f5] in <de80282032774528af67235d529e39b9>:0 
> UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
> UnityEngine.DebugLogHandler:LogException(Exception, Object)
> UnityEngine.Logger:LogException(Exception, Object)
> UnityEngine.Debug:LogException(Exception)
> ManufacturingPowerUI:ChangePowerSettings(Boolean, Boolean, PowerSourceType, Boolean)
> ManufacturingPanel:EnterManu(manufacturing)
> manufacturing:Enter()
> CraftingBase:Use()
> CraftingBase:Interact()
> InteractObjects:UseInteractable()
> GameController:Update()
>  
> (Filename: <b33094dda4904923a301738eea94aa76> Line: 0)
> 
> System.NullReferenceException
>   at (wrapper managed-to-native) UnityEngine.GameObject.SetActive(UnityEngine.GameObject,bool)
>   at Slot.HideTradeUI () [0x0000a] in <de80282032774528af67235d529e39b9>:0  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
> 
> System.NullReferenceException
>   at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
>   at SlotController.CaptureSlot () [0x0001c] in <de80282032774528af67235d529e39b9>:0 
>   at CraftingBase.Enter () [0x00038] in <de80282032774528af67235d529e39b9>:0  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[Slot5.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13300909/Slot5.zip)

**Comment by Kastuk** [comment] 2023-11-08 21:19
Shabby woodstove and sink have same bug.

**Comment by Oskutin** [comment] 2023-11-08 21:22
I can't reproduce this, even with loading the save :/

**Comment by Kastuk** [comment] 2023-11-09 20:03
After some game restarts this bug is gone both for stoves and sinks.

**Comment by Nextej** [comment] 2023-11-09 20:11
Also happens to the small moonshine distillery at Kolhola's A11
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/68ac2f4f-bdda-46d1-9177-d1b33fad9e24)

**Comment by Nextej** [comment] 2023-11-11 22:18
Affects player-placed stuff too (like Mashing Tuns)

**Comment by Nextej** [comment] 2023-11-12 15:36
[Miko_Mortley.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13328452/Miko_Mortley.zip)
On this character, load up autosave, go to the sauna and open the UI, wait till Thursday 11:07 without skipping time

**Comment by Oskutin** [comment] 2023-11-14 07:35
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/2bffa32e-f260-4a11-ad22-b65838b29a5d)

**Comment by rosysyntax** [comment] 2023-11-18 23:29
Can confirm, though I cannot reliably reproduce. However, reloading a save seems to fix it. I have encountered the bug, saved, then reloaded that save, and it is fixed.

**Comment by djguy4** [comment] 2024-04-02 15:22
Version: 0.3.38

Log file: 
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/14839229/Player.log)

Save file: 
[Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14839236/Slot3.zip)


Hello, I think my save file can reliably reproduce this bug. Although in my case it breaks the wood stove and the mashing tun. I found out how to reproduce this bug reliably:

1. Quit the game to desktop.
2. Start the game.
3. Load this save file.
4. The mashing tun and the wood stove will be broken.

If you try loading the save file the second time, the bug will be fixed. Make sure to load this save file after starting the game for the first time. Do not load any save file before loading this save file. Quit the game to desktop first if needed.

**Comment by Zuntti** [comment] 2024-04-03 11:51
Fixed

**Closed by Zuntti** 2024-04-03 11:51 UTC
Labels: Bug, Random

**Comment by Taco-Cat1** [comment] 2024-04-12 04:34
Unfortunutly, I am expiriencing both bugs and am trying to send you a save in issue#1911
