### ISSUE TITLE
Dropping items can throw exceptions if placement fails

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#134] opened 2023-04-25 22:24 UTC
https://user-images.githubusercontent.com/8556074/234417384-dbff8707-a3e8-405a-8e3f-6ddc9286b735.mp4

If the game fails to find a spot for a dropped item, the item will remain stuck on your screen along with this exception:

```NullReferenceException: Object reference not set to an instance of an object
  at ItemOperations.InstantiateItem (UnityEngine.GameObject prefab, UnityEngine.Vector3 spawnPosition, UnityEngine.RaycastHit hitinfo) [0x000c4] in <fb8fdaaf98ee4dd08547a331fa72ae37>:0 
  at ItemOperations.SpawnItemToPosition (ItemStack item, UnityEngine.Vector3 spawnPosition, UnityEngine.RaycastHit hit) [0x0002d] in <fb8fdaaf98ee4dd08547a331fa72ae37>:0 
  at ItemOperations.DropItem (ItemStack item, UnityEngine.GameObject dropper) [0x00189] in <fb8fdaaf98ee4dd08547a331fa72ae37>:0 
  at ItemData.DropItem (System.Int32 amount, System.Boolean dropAll) [0x00039] in <fb8fdaaf98ee4dd08547a331fa72ae37>:0 
  at ItemData.OnEndDrag (UnityEngine.EventSystems.PointerEventData eventData) [0x0004e] in <fb8fdaaf98ee4dd08547a331fa72ae37>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IEndDragHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00007] in <fa5a66f01464494f846478c0446b9fad>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00063] in <fa5a66f01464494f846478c0446b9fad>:0 ```

**Comment by Oskutin** [comment] 2023-04-25 22:34
Duplicate of this: https://github.com/loiste-interactive/Obenseuer-Issues/issues/19 
But keeping this issue and closing the other as this is more detailed.

**Comment by Oskutin** [comment] 2023-04-25 22:38
Fixed

**Closed by Oskutin** 2023-04-25 22:38 UTC
Labels: bug
